[package]
name = "organizer"
version = "0.1.0"
edition = "2024"

[dependencies]
digest = "0.10.7"
image = "0.25.6"
rawloader = "0.37.1"
sha2 = "0.10.9"
walkdir = "2.5.0"
globset = "0.4"
clap = { version = "4.5.4", features = ["derive"] }
indicatif = "0.17"
ctrlc = "3.4"
